### ISSUE TITLE
Decode bug when running sra-downloader ERR2177760 in ide terminal

### ISSUE THREAD

**Issue by FoMelanie** [bioinf-mcb/sra-downloader#7]
Hello,

I tried the following command present in the readme as an example after installing sra-downloader as a package. I am working with python 3.10.0b3 in my virtual environment and added the sra-downloader package using poetry.
The sra-downloader package is installed and prints well the different possible commands after running `sra-downloader -h`

`sra-downloader ERR2177760`

And I get the following error, after the `Processing: ERR2177760` line:

```
File "...\sra_downloader\download.py", line 40, in _call
    if res.stderr.decode():
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 12: invalid start byte
```

I tried using the python version specified in the readme (3.6.8) but it did not change the error output.

Is there something I am missing here ?

Thank you in advance

**Comment by wwydmanski** [comment]
It should be working in 1.0.7, we're now reading the subprocess outptut in plaintext to avoid encoding problems
